### ISSUE TITLE
clone the repo and get the skeleton running on your local system

### ISSUE THREAD

**Issue by shouryan01** [Google-Developer-Student-Club-Dearborn/hd2-app#1]

**Comment by alielzei** [comment]
Works for me. Check image.

<img width="542" alt="Screenshot 2023-04-18 at 10 50 12 PM" src="https://user-images.githubusercontent.com/16546209/232954173-32738afc-0585-455f-8e00-72c4ece7ccf3.png">

I was able to run this by installing flutter. 

After installing flutter on your system run `flutter doctor -v` to find any problems and resolve them.

Then `flutter run` will run your app on an available device. Possible devices include:
- A running iOS Simulator
-  A running Android device Emulator
-  Browser
