### ISSUE TITLE
Create information cards; Add text pending

### ISSUE THREAD

**Issue by shouryan01** [Google-Developer-Student-Club-Dearborn/hd2-app#17]
If you have an iPhone, you'll know exactly what this issue is referencing. 

[Here is a stackoverflow submission where someone has the code for exactly what we need.](https://stackoverflow.com/questions/62575091/possible-to-copy-ios-app-store-transition-using-flutter), here is the corresponding [github link](https://github.com/HelloJunWei/app_store_transition).

Give this a try and let me know if you're able to implement this. As always, please make everything very modular. So create this as a new widget and import it in the "Information" widget that you should've created based on #16 .

For a demo render 3 widget and made the corners rounded. The opening and closing animations should have a balance between smoothness and speed.

**Comment by alielzei** [comment]
Found this cool library, that makes use of the Hero widget as well, check demo video. I was trying to scroll the other way to show that it doesnt collapse like that.

https://user-images.githubusercontent.com/16546209/235337955-f7d9908c-bcc3-4f21-833a-2cb57a58f4c7.mov

**Comment by shouryan01** [comment]
Yeah that looks like exactly what we need! Still need to find a way to add text to that though

**Comment by alielzei** [comment]
I anticipate adding text should be easy, will work on it

**Comment by alielzei** [comment]
https://user-images.githubusercontent.com/16546209/236724340-d1eff243-f4c5-487e-9f5a-36a7bc22ca4f.mp4
