### ISSUE TITLE
Fix splash screen for android

### ISSUE THREAD

**Issue by shouryan01** [Google-Developer-Student-Club-Dearborn/hd2-app#2]

**Comment by shouryan01** [comment]
Here is a pub.dev package that might do the trick: https://pub.dev/packages/animated_splash_screen
Here's two others:
https://pub.dev/packages/flutter_native_splash
https://pub.dev/packages/splashscreen

It doesn't have to be animated but that would be a plus. According to Apple's rules all apps must come with a splash screen. The default one is just a white screen but I think we can show a logo.

**Comment by alielzei** [comment]
Spent the night experimenting and it is better to handle launch screens natively on each platform (Android, iOS) as splash screens are handled by the OS not flutter. The first two packages don't do much of a great job. To have an animation, a good thing to do is to wrap our app in a VideoPlayer widget that will just play the animation after the native initial static launch screen is done. 

Something like in the end of this video. 

https://www.youtube.com/watch?v=ySaVFCpK4M8&t=1s&ab_channel=FlutterUIDev

Here's a video of what I got done on iOS. 

https://user-images.githubusercontent.com/16546209/233344936-18e8066f-7d8d-4b7e-a8aa-589f02baf063.mov

**Comment by alielzei** [comment]
Reopening what I closed because this needs testing on android

**Comment by shouryan01** [comment]
https://user-images.githubusercontent.com/32345320/235332396-b1ed6e90-f8e7-4e8c-bb17-e3f0169ba0ef.mov

You're right. The behavior is a little bit weird on android. Tested on pixel 3a emulator.

**Comment by alielzei** [comment]
For iOS I added a black screen from XCode.

For android we need to do a similar thing. Probably need to follow this: https://docs.flutter.dev/platform-integration/android/splash-screen

Looking at the video you posted.

I think also the splash screen didnt correctly fade out and I suspect the reason being it is in debug mode and it is running on an emulator.

**Comment by alielzei** [comment]
@shouryan01 Can you reproduce on android and ios and see if the splash screen is acceptable then merge to development?
