### ISSUE TITLE
Need to create different sized logos for the app launcher icons

### ISSUE THREAD

**Issue by shouryan01** [Google-Developer-Student-Club-Dearborn/hd2-app#25]
Currently the default app launcher icon is the flutter icon. We need to create the appropriate corresponding icons for various screen sizes

**Comment by shouryan01** [comment]
@alielzei @shrestharosy we need the app icons to be done asap for the release

**Comment by shrestharosy** [comment]
Open PR [here](https://github.com/Google-Developer-Student-Club-Dearborn/hd2-app/pull/44)
