### ISSUE TITLE
We need to display an agenda on the first page

### ISSUE THREAD

**Issue by shouryan01** [Google-Developer-Student-Club-Dearborn/hd2-app#26]
Please try to [implement this](https://pub.dev/packages/syncfusion_flutter_calendar#get-the-demo-application), specifially the schedule view. This resembles the Google Calendar UI and should be sufficient for our needs.

**Comment by khanabdu25** [comment]
Can you please list all the specifications here for reference.. thank you

**Comment by khanabdu25** [comment]
Also how the data for the calendar is to be pulled

**Comment by shouryan01** [comment]
Data for this doesn't need to be pulled as a requirement. We will make that a stretch goal once we have everything else working. You were right on the call, we will pull the data using the google calendar api. For now, we need to submit an app for App store review asap so we will hold off on that.


Please copy the agenda [from here](https://archive.hd1.hackdearborn.org/). To get the agenda, click on the "11" and "12" in the calendar and you'll see a list of events. You can alternatively use the list [from Google Calendar.](https://calendar.google.com/calendar/u/0/r?cid=Y19lNWY2NzViMmZkYTY4MDJhOTM2YWE5MzBjNjhmMDkwYjgyNzg2NzUwZGYxYjcyNzRmMzg2MTEyYjIwNDM2N2Q4QGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20).

**Comment by shouryan01** [comment]
Please include "Current time indicator"
![](https://cdn.syncfusion.com/content/images/FTControl/Flutter/calendar/current_time_indicator.png)

and "Custom start and end hours" based on the schedules listed.

**Comment by shouryan01** [comment]
Can you create a demo with "Day", "Schedule" and "Timeline day" view?
![](https://cdn.syncfusion.com/content/images/FTControl/Calendar/flutter-calendar-views.png)
