### ISSUE TITLE
Increase brightness temporarily

### ISSUE THREAD

**Issue by shouryan01** [Google-Developer-Student-Club-Dearborn/hd2-app#31]
In lots of apps, when the screen to scan qr code is shown, the brightness is increased to 100% automatically. Can you show a demo of this behavior for the qr code page?

**Comment by shouryan01** [comment]
@shrestharosy do you want to open a pr for your changes? it looked good during the demo

**Comment by shrestharosy** [comment]
Completed and opened PR [here](https://github.com/Google-Developer-Student-Club-Dearborn/hd2-app/pull/39)
