### ISSUE TITLE
Update the schedule with the confirmed agenda

### ISSUE THREAD

**Issue by shouryan01** [Google-Developer-Student-Club-Dearborn/hd2-app#47]
Here is the updated agenda, can you replace the existing data with the agenda from here?

https://docs.google.com/document/d/1aW-soEHR6leieip9rt3pTyCWDiX3orr-d1h5BSMJpxA/edit?usp=sharing

**Comment by alielzei** [comment]
I used firebase to store the updated agenda in #49, the app should be pulling the data and showing it.

**Comment by shouryan01** [comment]
I hard coded this info for now, once the firebase is working then we can switch over. Will it be expensive to pull in the schedule every time or are you working on caching and fetch if there are updates
